engines:
  eslint:
      enabled: true

ratings:
  paths:
  - "frontend-angularjs/www/app/**"

exclude_paths:
- "Backend/**/*"
- "frontend-angularjs/gulp/**/*"
- "frontend-angularjs/*.js"
- "frontend-angularjs/*.json"
- "frontend-angularjs/*.xml"
- "*.md"
- "*.xml"
- "LICENSE"